### ISSUE TITLE
Unable to Decompose a Polygon with Holes

### ISSUE THREAD

**Issue by TheDeafOne** [LostFan123/pode#33]
I'm trying to decompose a polygon with holes as defined by the following interior and exterior:
```
ext = [(0, 0), (0, 2), (2, 2), (2, 0), (0, 0)]
interior = [(0.25, 0.25), (0.25, 1.25), (1.25, 1.25), (1.25, 0.25)]
contour = Contour([Point(*point) for point in ext + interior])
polygon = DPolygon(contour)
requirements = [Requirement(0.5), Requirement(0.5, point=Point(2,2))]
```
I get the following error:
```
Traceback (most recent call last):
  File "C:\...\test_poly_decomp.py", line 22, in <module>
    parts = divide(polygon, requirements)
  File "C:\...\Python\Python310\site-packages\pode\pode.py", line 
328, in divide
    edge = graph[current_polygon][neighbor]['side']
  File "C:\...\Python\Python310\site-packages\networkx\classes\coreviews.py", line 54, in __getitem__
    return self._atlas[key]
KeyError: None
```
What am I doing wrong?

**Comment by GeorgySk** [comment]
@TheDeafOne The issue is with how the contour and the polygon are constructed. 
If you try to validate the contour by running `contour.validate()` you should get `ValueError: Contour should not be self-intersecting.`.  

What you probably wanted to do instead was the following:
```python
ext = [(0, 0), (0, 2), (2, 2), (2, 0), (0, 0)]
interior = [(0.25, 0.25), (0.25, 1.25), (1.25, 1.25), (1.25, 0.25)]
border = Contour([Point(*point) for point in ext[:-1]])
hole = Contour([Point(*point) for point in interior])
polygon = DPolygon(border, [hole])
requirements = [Requirement(0.5), Requirement(0.5, point=Point(2,2))]
parts = divide(polygon, requirements)
```
Note that the `Contour` shouldn't have the last vertex equal to the first one. Also note how the `Polygon` is constructed from two parameters -- a `Contour` defining a border of the polygon and a list of `Contour` object defining holes (in your case it's just one). 
The code above gives me:
```python
[Polygon(Contour([Point(Fraction(0, 1), Fraction(0, 1)), 
                  Point(Fraction(2, 1), Fraction(0, 1)), 
                  Point(Fraction(2, 1), Fraction(2, 1)), 
                  Point(Fraction(5, 4), Fraction(5, 4)), 
                  Point(Fraction(5, 4), Fraction(1, 4)),
                  Point(Fraction(1, 4), Fraction(1, 4))]), []), 
 Polygon(Contour([Point(Fraction(0, 1), Fraction(0, 1)), 
                  Point(Fraction(1, 4), Fraction(1, 4)),
                  Point(Fraction(1, 4), Fraction(5, 4)), 
                  Point(Fraction(5, 4), Fraction(5, 4)), 
                  Point(Fraction(2, 1), Fraction(2, 1)), 
                  Point(Fraction(0, 1), Fraction(2, 1))]), [])]
```
which satisfies the given requirements:
```python
>>> assert parts[0].area == parts[1].area
>>> assert Point(2, 2) in parts[1]
```
